// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTT2EMY0L3ulDq5hrlZZk5HkfnVoijvgI',
    appId: '1:21921704445:android:041600083f984c361b5194',
    messagingSenderId: '21921704445',
    projectId: 'taskly-f875f',
    storageBucket: 'taskly-f875f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB4pITBVWXc9qZG-6YCJUSCNYiLqlYosc',
    appId: '1:21921704445:ios:6299bd44d0d375581b5194',
    messagingSenderId: '21921704445',
    projectId: 'taskly-f875f',
    storageBucket: 'taskly-f875f.firebasestorage.app',
    androidClientId: '21921704445-7tsitbd62gedhiuv30ieoa8m4bnmh9fn.apps.googleusercontent.com',
    iosClientId: '21921704445-t8vhjitnued3ped0tjiqbrmmkupgpaso.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskly',
  );
}
